In [40]:
import os
import pandas as pd

# extracting channel names and val_acc

In [89]:
# channel names 
files = []
dropped_channels =[]
directory = r"F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12"

for filename in os.listdir(directory):
     #print(filename)
     files.append(filename)

     channel = filename[-7:]
     if channel[0] == '_':
        channel = channel[1:]
     if channel[:2]=='p_':
        channel= channel[2:]

     dropped_channels.append(channel)
     print(channel)
     
print(f'{len(files)} files found and {len(dropped_channels)} dropped channels  found')

AF3_AF4
AF3_F3
AF3_F4
AF3_F7
AF3_F8
AF3_FC5
AF3_FC6
AF3_O1
AF3_O2
AF3_P7
AF3_P8
AF3_T7
AF3_T8
AF4_F3
AF4_F4
AF4_F7
AF4_F8
AF4_FC5
AF4_FC6
AF4_O1
AF4_O2
AF4_P7
AF4_P8
AF4_T7
AF4_T8
F3_F4
F3_F7
F3_F8
F3_FC5
F3_FC6
F3_O1
F3_O2
F3_P7
F3_P8
F3_T7
F3_T8
F4_F7
F4_F8
F4_FC5
F4_FC6
F4_O1
F4_O2
F4_P7
F4_P8
F4_T7
F4_T8
F7_F8
F7_FC5
F7_FC6
F7_O1
F7_O2
F7_P7
F7_P8
F7_T7
F7_T8
F8_FC5
F8_FC6
F8_O1
F8_O2
F8_P7
F8_P8
F8_T7
F8_T8
FC5_FC6
FC5_O1
FC5_O2
FC5_P7
FC5_P8
FC5_T7
FC5_T8
FC6_O1
FC6_O2
FC6_P7
FC6_P8
FC6_T7
FC6_T8
O1_O2
O1_P7
O1_P8
O1_T7
O1_T8
O2_P7
O2_P8
O2_T7
O2_T8
P7_P8
P7_T7
P7_T8
P8_T7
P8_T8
T7_T8
91 files found and 91 dropped channels  found

In [90]:
#val acc
c=0
prev_csv = []
for root, dirs, files in os.walk(directory):
    for filename in files:
        if filename.endswith(".csv"):
            print(os.path.join(root, filename))
            c+=1
            prev_csv.append(os.path.join(root,filename))
print(f'{c} csv files found')

F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF3_AF4\keep12_drop_AF3_AF4_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF3_F3\keep12_drop_AF3_F3_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF3_F4\keep12_drop_AF3_F4_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF3_F7\keep12_drop_AF3_F7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF3_F8\keep12_drop_AF3_F8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF3_FC5\keep12_drop_AF3_FC5_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF3_FC6\keep12_drop_AF3_FC6_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF3_O1\keep12_drop_AF3_O1_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF3_O2\keep12_drop_AF3_O2_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF3_P7\keep12_drop_AF3_P7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF3_P8\keep12_drop_AF3_P8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF3_T7\keep12_drop_AF3_T7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF3_T8\keep12_drop_AF3_T8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF4_F3\keep12_drop_AF4_F3_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF4_F4\keep12_drop_AF4_F4_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF4_F7\keep12_drop_AF4_F7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF4_F8\keep12_drop_AF4_F8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF4_FC5\keep12_drop_AF4_FC5_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF4_FC6\keep12_drop_AF4_FC6_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF4_O1\keep12_drop_AF4_O1_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF4_O2\keep12_drop_AF4_O2_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF4_P7\keep12_drop_AF4_P7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF4_P8\keep12_drop_AF4_P8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF4_T7\keep12_drop_AF4_T7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_AF4_T8\keep12_drop_AF4_T8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F3_F4\keep12_drop_F3_F4_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F3_F7\keep12_drop_F3_F7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F3_F8\keep12_drop_F3_F8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F3_FC5\keep12_drop_F3_FC5_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F3_FC6\keep12_drop_F3_FC6_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F3_O1\keep12_drop_F3_O1_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F3_O2\keep12_drop_F3_O2_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F3_P7\keep12_drop_F3_P7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F3_P8\keep12_drop_F3_P8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F3_T7\keep12_drop_F3_T7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F3_T8\keep12_drop_F3_T8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F4_F7\keep12_drop_F4_F7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F4_F8\keep12_drop_F4_F8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F4_FC5\keep12_drop_F4_FC5_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F4_FC6\keep12_drop_F4_FC6_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F4_O1\keep12_drop_F4_O1_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F4_O2\keep12_drop_F4_O2_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F4_P7\keep12_drop_F4_P7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F4_P8\keep12_drop_F4_P8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F4_T7\keep12_drop_F4_T7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F4_T8\keep12_drop_F4_T8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F7_F8\keep12_drop_F7_F8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F7_FC5\keep12_drop_F7_FC5_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F7_FC6\keep12_drop_F7_FC6_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F7_O1\keep12_drop_F7_O1_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F7_O2\keep12_drop_F7_O2_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F7_P7\keep12_drop_F7_P7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F7_P8\keep12_drop_F7_P8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F7_T7\keep12_drop_F7_T7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F7_T8\keep12_drop_F7_T8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F8_FC5\keep12_drop_F8_FC5_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F8_FC6\keep12_drop_F8_FC6_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F8_O1\keep12_drop_F8_O1_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F8_O2\keep12_drop_F8_O2_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F8_P7\keep12_drop_F8_P7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F8_P8\keep12_drop_F8_P8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F8_T7\keep12_drop_F8_T7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_F8_T8\keep12_drop_F8_T8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_FC5_FC6\keep12_drop_FC5_FC6_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_FC5_O1\keep12_drop_FC5_O1_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_FC5_O2\keep12_drop_FC5_O2_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_FC5_P7\keep12_drop_FC5_P7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_FC5_P8\keep12_drop_FC5_P8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_FC5_T7\keep12_drop_FC5_T7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_FC5_T8\keep12_drop_FC5_T8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_FC6_O1\keep12_drop_FC6_O1_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_FC6_O2\keep12_drop_FC6_O2_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_FC6_P7\keep12_drop_FC6_P7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_FC6_P8\keep12_drop_FC6_P8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_FC6_T7\keep12_drop_FC6_T7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_FC6_T8\keep12_drop_FC6_T8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_O1_O2\keep12_drop_O1_O2_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_O1_P7\keep12_drop_O1_P7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_O1_P8\keep12_drop_O1_P8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_O1_T7\keep12_drop_O1_T7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_O1_T8\keep12_drop_O1_T8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_O2_P7\keep12_drop_O2_P7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_O2_P8\keep12_drop_O2_P8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_O2_T7\keep12_drop_O2_T7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_O2_T8\keep12_drop_O2_T8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_P7_P8\keep12_drop_P7_P8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_P7_T7\keep12_drop_P7_T7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_P7_T8\keep12_drop_P7_T8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_P8_T7\keep12_drop_P8_T7_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_P8_T8\keep12_drop_P8_T8_history.csv
F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\keep12\keep12_drop_T7_T8\keep12_drop_T7_T8_history.csv
91 csv files found

In [91]:

val_acc  = [] 
for i in prev_csv:
    df  = pd.read_csv(i)
    val_acc.append(df['val_accuracy'].max())
    print(df['val_accuracy'].max())
len(val_acc)

0.93632709980011
0.8840482831001282
0.9222519993782043
0.9075067043304444
0.930294930934906
0.9121983647346495
0.9336460828781128
0.8592493534088135
0.9088472127914428
0.9128686189651488
0.8981233239173889
0.8853887319564819
0.8994638323783875
0.9081769585609436
0.8927614092826843
0.9182305335998536
0.9155495762825012
0.9054960012435912
0.9115281701087952
0.910857915878296
0.8277480006217957
0.8947721123695374
0.930294930934906
0.9041554927825928
0.7546916604042053
0.9148793816566468
0.9142091274261476
0.924262762069702
0.93632709980011
0.9316353797912598
0.9269437193870544
0.932305634021759
0.8920911550521851
0.934316337108612
0.9155495762825012
0.817694365978241
0.9202412962913512
0.9155495762825012
0.9162198305130004
0.9189007878303528
0.9202412962913512
0.9296246767044068
0.9155495762825012
0.7312332391738892
0.9215817451477052
0.9115281701087952
0.9001340270042419
0.8552278876304626
0.924262762069702
0.9061661958694458
0.9041554927825928
0.9309651255607604
0.9249329566955566
0.9142091274261476
0.8579088449478149
0.8666219711303711
0.845174252986908
0.9121983647346495
0.819705069065094
0.919571042060852
0.917560338973999
0.924262762069702
0.8713136911392212
0.9021447896957396
0.8746649026870728
0.8217158317565918
0.8156836628913879
0.7553619146347046
0.9269437193870544
0.9088472127914428
0.924262762069702
0.8250670433044434
0.8036193251609802
0.8089812397956848
0.9014745354652404
0.9168900847434998
0.8833780288696289
0.9249329566955566
0.9269437193870544
0.910857915878296
0.9202412962913512
0.872654139995575
0.9081769585609436
0.9202412962913512
0.9115281701087952
0.7701072096824646
0.7788203954696655
0.924262762069702
0.919571042060852
0.9021447896957396
0.8994638323783875

91

# modifying excel file

In [100]:
excel_main = r"F:\WORK\Thesis\code_reducing_channel\outputs\guinea_outputs\outputs_CNN_LSTM\CNN_LSTM_AllCombos_Summary.xlsx"

df_main  = pd.read_excel(excel_main)

df_main.head(10)

,model,title,fname,n_keep,kept,dropped,val_acc,val_loss,auc,precision,recall,f1,cohen_kappa,tn,fp,fn,tp,train_time_s
0,CNN_LSTM,"Dropped: FC6, O1",keep12_drop_FC6_O1,12,"AF3, AF4, F3, F4, F7, F8, FC5, O2, P7, P8, T7, T8","FC6, O1",92.426276,0.210732,0.977353,92.345679,93.617021,92.977004,0.847597,631,62,51,748,348.6
1,CNN_LSTM,"Dropped: FC6, O2",keep12_drop_FC6_O2,12,"AF3, AF4, F3, F4, F7, F8, FC5, O1, P7, P8, T7, T8","FC6, O2",82.506704,0.436756,0.894975,83.046683,84.605757,83.818971,0.647854,555,138,123,676,142.7
2,CNN_LSTM,"Dropped: FC6, P7",keep12_drop_FC6_P7,12,"AF3, AF4, F3, F4, F7, F8, FC5, O1, O2, P8, T7, T8","FC6, P7",80.361933,0.462855,0.872684,78.881279,86.483104,82.507463,0.602315,508,185,108,691,161.4
3,CNN_LSTM,"Dropped: FC6, P8",keep12_drop_FC6_P8,12,"AF3, AF4, F3, F4, F7, F8, FC5, O1, O2, P7, T7, T8","FC6, P8",80.898124,0.456844,0.866547,84.175532,79.224030,81.624758,0.617744,574,119,166,633,134.4
4,CNN_LSTM,"Dropped: FC6, T7",keep12_drop_FC6_T7,12,"AF3, AF4, F3, F4, F7, F8, FC5, O1, O2, P7, P8, T8","FC6, T7",90.147454,0.258988,0.962233,92.337662,88.986233,90.630975,0.802498,634,59,88,711,246.1
5,CNN_LSTM,"Dropped: FC6, T8",keep12_drop_FC6_T8,12,"AF3, AF4, F3, F4, F7, F8, FC5, O1, O2, P7, P8, T7","FC6, T8",91.689008,0.244496,0.969074,93.661061,90.613267,92.111959,0.833352,644,49,75,724,315.7
6,CNN_LSTM,"Dropped: O1, O2",keep12_drop_O1_O2,12,"AF3, AF4, F3, F4, F7, F8, FC5, FC6, P7, P8, T7...","O1, O2",88.337803,0.299331,0.950263,89.013733,89.236546,89.125000,0.765528,605,88,86,713,297.5
7,CNN_LSTM,"Dropped: O1, P7",keep12_drop_O1_P7,12,"AF3, AF4, F3, F4, F7, F8, FC5, FC6, O2, P8, T7...","O1, P7",92.493296,0.248300,0.972984,93.757962,92.115144,92.929293,0.849306,644,49,63,736,433.6
8,CNN_LSTM,"Dropped: O1, P8",keep12_drop_O1_P8,12,"AF3, AF4, F3, F4, F7, F8, FC5, FC6, O2, P7, T7...","O1, P8",92.694372,0.375533,0.977141,92.383292,94.117647,93.242405,0.852935,631,62,47,752,435.2
9,CNN_LSTM,"Dropped: O1, T7",keep12_drop_O1_T7,12,"AF3, AF4, F3, F4, F7, F8, FC5, FC6, O2, P7, P8...","O1, T7",91.085792,0.259519,0.959919,91.111111,92.365457,91.733996,0.820623,621,72,61,738,272.3

In [93]:
prev_rows = []
j = 0
for i in dropped_channels:



    prev_rows.append({'dropped': i,

                     'val_acc': val_acc[j] 
                      })

    j+=1                  

print(prev_rows)
len(prev_rows)

[{'dropped': 'AF3_AF4', 'val_acc': np.float64(0.93632709980011)}, {'dropped': 'AF3_F3', 'val_acc': np.float64(0.8840482831001282)}, {'dropped': 'AF3_F4', 'val_acc': np.float64(0.9222519993782043)}, {'dropped': 'AF3_F7', 'val_acc': np.float64(0.9075067043304444)}, {'dropped': 'AF3_F8', 'val_acc': np.float64(0.930294930934906)}, {'dropped': 'AF3_FC5', 'val_acc': np.float64(0.9121983647346495)}, {'dropped': 'AF3_FC6', 'val_acc': np.float64(0.9336460828781128)}, {'dropped': 'AF3_O1', 'val_acc': np.float64(0.8592493534088135)}, {'dropped': 'AF3_O2', 'val_acc': np.float64(0.9088472127914428)}, {'dropped': 'AF3_P7', 'val_acc': np.float64(0.9128686189651488)}, {'dropped': 'AF3_P8', 'val_acc': np.float64(0.8981233239173889)}, {'dropped': 'AF3_T7', 'val_acc': np.float64(0.8853887319564819)}, {'dropped': 'AF3_T8', 'val_acc': np.float64(0.8994638323783875)}, {'dropped': 'AF4_F3', 'val_acc': np.float64(0.9081769585609436)}, {'dropped': 'AF4_F4', 'val_acc': np.float64(0.8927614092826843)}, {'dropped': 'AF4_F7', 'val_acc': np.float64(0.9182305335998536)}, {'dropped': 'AF4_F8', 'val_acc': np.float64(0.9155495762825012)}, {'dropped': 'AF4_FC5', 'val_acc': np.float64(0.9054960012435912)}, {'dropped': 'AF4_FC6', 'val_acc': np.float64(0.9115281701087952)}, {'dropped': 'AF4_O1', 'val_acc': np.float64(0.910857915878296)}, {'dropped': 'AF4_O2', 'val_acc': np.float64(0.8277480006217957)}, {'dropped': 'AF4_P7', 'val_acc': np.float64(0.8947721123695374)}, {'dropped': 'AF4_P8', 'val_acc': np.float64(0.930294930934906)}, {'dropped': 'AF4_T7', 'val_acc': np.float64(0.9041554927825928)}, {'dropped': 'AF4_T8', 'val_acc': np.float64(0.7546916604042053)}, {'dropped': 'F3_F4', 'val_acc': np.float64(0.9148793816566468)}, {'dropped': 'F3_F7', 'val_acc': np.float64(0.9142091274261476)}, {'dropped': 'F3_F8', 'val_acc': np.float64(0.924262762069702)}, {'dropped': 'F3_FC5', 'val_acc': np.float64(0.93632709980011)}, {'dropped': 'F3_FC6', 'val_acc': np.float64(0.9316353797912598)}, {'dropped': 'F3_O1', 'val_acc': np.float64(0.9269437193870544)}, {'dropped': 'F3_O2', 'val_acc': np.float64(0.932305634021759)}, {'dropped': 'F3_P7', 'val_acc': np.float64(0.8920911550521851)}, {'dropped': 'F3_P8', 'val_acc': np.float64(0.934316337108612)}, {'dropped': 'F3_T7', 'val_acc': np.float64(0.9155495762825012)}, {'dropped': 'F3_T8', 'val_acc': np.float64(0.817694365978241)}, {'dropped': 'F4_F7', 'val_acc': np.float64(0.9202412962913512)}, {'dropped': 'F4_F8', 'val_acc': np.float64(0.9155495762825012)}, {'dropped': 'F4_FC5', 'val_acc': np.float64(0.9162198305130004)}, {'dropped': 'F4_FC6', 'val_acc': np.float64(0.9189007878303528)}, {'dropped': 'F4_O1', 'val_acc': np.float64(0.9202412962913512)}, {'dropped': 'F4_O2', 'val_acc': np.float64(0.9296246767044068)}, {'dropped': 'F4_P7', 'val_acc': np.float64(0.9155495762825012)}, {'dropped': 'F4_P8', 'val_acc': np.float64(0.7312332391738892)}, {'dropped': 'F4_T7', 'val_acc': np.float64(0.9215817451477052)}, {'dropped': 'F4_T8', 'val_acc': np.float64(0.9115281701087952)}, {'dropped': 'F7_F8', 'val_acc': np.float64(0.9001340270042419)}, {'dropped': 'F7_FC5', 'val_acc': np.float64(0.8552278876304626)}, {'dropped': 'F7_FC6', 'val_acc': np.float64(0.924262762069702)}, {'dropped': 'F7_O1', 'val_acc': np.float64(0.9061661958694458)}, {'dropped': 'F7_O2', 'val_acc': np.float64(0.9041554927825928)}, {'dropped': 'F7_P7', 'val_acc': np.float64(0.9309651255607604)}, {'dropped': 'F7_P8', 'val_acc': np.float64(0.9249329566955566)}, {'dropped': 'F7_T7', 'val_acc': np.float64(0.9142091274261476)}, {'dropped': 'F7_T8', 'val_acc': np.float64(0.8579088449478149)}, {'dropped': 'F8_FC5', 'val_acc': np.float64(0.8666219711303711)}, {'dropped': 'F8_FC6', 'val_acc': np.float64(0.845174252986908)}, {'dropped': 'F8_O1', 'val_acc': np.float64(0.9121983647346495)}, {'dropped': 'F8_O2', 'val_acc': np.float64(0.819705069065094)}, {'dropped': 'F8_P7', 'val_acc': np.float64(0.919571042060852)}, {'dropped': 'F8_P8', 'val_acc': np.float64(0.917560338973999)}, {'dropped': 'F8_T7', 'val_acc': np.float64(0.924262762069702)}, {'dropped': 'F8_T8', 'val_acc': np.float64(0.8713136911392212)}, {'dropped': 'FC5_FC6', 'val_acc': np.float64(0.9021447896957396)}, {'dropped': 'FC5_O1', 'val_acc': np.float64(0.8746649026870728)}, {'dropped': 'FC5_O2', 'val_acc': np.float64(0.8217158317565918)}, {'dropped': 'FC5_P7', 'val_acc': np.float64(0.8156836628913879)}, {'dropped': 'FC5_P8', 'val_acc': np.float64(0.7553619146347046)}, {'dropped': 'FC5_T7', 'val_acc': np.float64(0.9269437193870544)}, {'dropped': 'FC5_T8', 'val_acc': np.float64(0.9088472127914428)}, {'dropped': 'FC6_O1', 'val_acc': np.float64(0.924262762069702)}, {'dropped': 'FC6_O2', 'val_acc': np.float64(0.8250670433044434)}, {'dropped': 'FC6_P7', 'val_acc': np.float64(0.8036193251609802)}, {'dropped': 'FC6_P8', 'val_acc': np.float64(0.8089812397956848)}, {'dropped': 'FC6_T7', 'val_acc': np.float64(0.9014745354652404)}, {'dropped': 'FC6_T8', 'val_acc': np.float64(0.9168900847434998)}, {'dropped': 'O1_O2', 'val_acc': np.float64(0.8833780288696289)}, {'dropped': 'O1_P7', 'val_acc': np.float64(0.9249329566955566)}, {'dropped': 'O1_P8', 'val_acc': np.float64(0.9269437193870544)}, {'dropped': 'O1_T7', 'val_acc': np.float64(0.910857915878296)}, {'dropped': 'O1_T8', 'val_acc': np.float64(0.9202412962913512)}, {'dropped': 'O2_P7', 'val_acc': np.float64(0.872654139995575)}, {'dropped': 'O2_P8', 'val_acc': np.float64(0.9081769585609436)}, {'dropped': 'O2_T7', 'val_acc': np.float64(0.9202412962913512)}, {'dropped': 'O2_T8', 'val_acc': np.float64(0.9115281701087952)}, {'dropped': 'P7_P8', 'val_acc': np.float64(0.7701072096824646)}, {'dropped': 'P7_T7', 'val_acc': np.float64(0.7788203954696655)}, {'dropped': 'P7_T8', 'val_acc': np.float64(0.924262762069702)}, {'dropped': 'P8_T7', 'val_acc': np.float64(0.919571042060852)}, {'dropped': 'P8_T8', 'val_acc': np.float64(0.9021447896957396)}, {'dropped': 'T7_T8', 'val_acc': np.float64(0.8994638323783875)}]

91

In [ ]:
#### alternative way ####
# for channel, acc in zip(dropped_channels, val_acc):
#     prev_rows.append({
#         "dropped": channel,
#         "val_acc": acc
#     })

In [108]:
prev_df = pd.DataFrame(
      prev_rows
  )
prev_df.head(10)

   dropped   val_acc
0  AF3_AF4  0.936327
1   AF3_F3  0.884048
2   AF3_F4  0.922252
3   AF3_F7  0.907507
4   AF3_F8  0.930295
5  AF3_FC5  0.912198
6  AF3_FC6  0.933646
7   AF3_O1  0.859249
8   AF3_O2  0.908847
9   AF3_P7  0.912869

# saving the excel file

In [115]:
prev_df.to_excel("fixed_all_cnn_lstm_guinea_summary.xlsx", index=False)

In [116]:
pd.read_excel("fixed_all_cnn_lstm_guinea_summary.xlsx")

    dropped   val_acc
0   AF3_AF4  0.936327
1    AF3_F3  0.884048
2    AF3_F4  0.922252
3    AF3_F7  0.907507
4    AF3_F8  0.930295
..      ...       ...
86    P7_T7  0.778820
87    P7_T8  0.924263
88    P8_T7  0.919571
89    P8_T8  0.902145
90    T7_T8  0.899464

[91 rows x 2 columns]